import { CleanupReport, CleanupMission, CitizenRank, UserProfile } from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'usr-1042',
  name: 'Hamza Khan',
  citizenNumber: 'SWL-1042',
  neighborhood: 'Farid Town, Sector 3',
  city: 'Sahiwal, Punjab',
  cleanPoints: 850,
  rank: 8,
  missionsReported: 4,
  missionsCleaned: 3,
  verifiedCleanups: 3,
  wasteDivertedKg: 64,
  streakDays: 7,
  badges: [
    {
      id: 'b1',
      name: 'First Cleanup',
      description: 'Complete your first verified cleanup mission in Sahiwal',
      icon: 'Award',
      unlocked: true,
      unlockedAt: 'Sep 2026',
      progress: { current: 1, total: 1 },
      category: 'cleanup',
    },
    {
      id: 'b2',
      name: 'Farid Town Guardian',
      description: 'Completed 3 neighborhood cleanup missions',
      icon: 'ShieldCheck',
      unlocked: true,
      unlockedAt: 'Sep 2026',
      progress: { current: 3, total: 3 },
      category: 'cleanup',
    },
    {
      id: 'b3',
      name: 'Neighborhood Hero',
      description: 'Amass 1,000+ CleanPoints keeping Sahiwal clean',
      icon: 'Crown',
      unlocked: false,
      progress: { current: 850, total: 1000 },
      category: 'points',
    },
  ],
};

export const MOCK_REPORTS: CleanupReport[] = [
  {
    id: 'rep-01',
    title: 'Plastic Litter near Fruit Mandi',
    category: 'Plastic Waste',
    locationName: 'Goal Chowk, High Street Corner',
    coordinates: { x: 48, y: 52 },
    status: 'Open',
    urgency: 'High',
    cleanPointsReward: 50,
    reportedAt: '25 mins ago',
    reporterName: 'Usman Ali',
    description: 'Heavy single-use plastic sacks and carton packaging accumulated behind market stalls.',
    upvotes: 14,
  },
  {
    id: 'rep-02',
    title: 'Overflowing Municipal Waste Bin',
    category: 'Overflowing Dumpster',
    locationName: 'Farid Town Central Commercial Area',
    coordinates: { x: 32, y: 38 },
    status: 'In Progress',
    urgency: 'Medium',
    cleanPointsReward: 25,
    reportedAt: '2 hours ago',
    reporterName: 'Ayesha Malik',
    description: 'Main neighborhood container full; municipal collection team notified and underway.',
    upvotes: 29,
  },
  {
    id: 'rep-03',
    title: 'Canal Bank Debris Clearing',
    category: 'Construction Debris',
    locationName: 'Lower Bari Doab Canal Road',
    coordinates: { x: 68, y: 28 },
    status: 'Verified',
    urgency: 'Low',
    cleanPointsReward: 10,
    reportedAt: 'Yesterday',
    reporterName: 'Bilal Mengrani',
    description: 'Rubble from walkway paving cleared and recycled with civic team coordination.',
    upvotes: 42,
  },
  {
    id: 'rep-04',
    title: 'Storm Drain Sediment Blockage',
    category: 'Drainage Blockage',
    locationName: 'College Road near Govt. Post Graduate College',
    coordinates: { x: 55, y: 64 },
    status: 'Open',
    urgency: 'High',
    cleanPointsReward: 50,
    reportedAt: '3 hours ago',
    reporterName: 'Zainab Bibi',
    description: 'Plastic bottles blocking drain grate right before monsoon street inlet.',
    upvotes: 19,
  },
  {
    id: 'rep-05',
    title: 'Montgomery Station Green Belt Trash',
    category: 'Greenery Cleanup',
    locationName: 'Railway Road Promenade',
    coordinates: { x: 38, y: 72 },
    status: 'Verified',
    urgency: 'Medium',
    cleanPointsReward: 25,
    reportedAt: '1 day ago',
    reporterName: 'Hamza Khan',
    description: 'Citizen volunteer drive bagged 18 sacks of wrapper litter around historical trees.',
    upvotes: 38,
  },
];

export const MOCK_MISSIONS: CleanupMission[] = [
  {
    id: 'mis-01',
    title: 'Farid Town Park Sunday Sweep',
    neighborhood: 'Farid Town Sector 2',
    date: 'Sunday, 28 Sep',
    time: '07:30 AM – 10:00 AM',
    participantsCount: 28,
    maxParticipants: 40,
    rewardPoints: 200,
    status: 'Active',
    organizer: 'Sahiwal Youth Environmental Guild',
    wasteTargetKg: 150,
    collectedKg: 95,
    description: 'Community cleanup of central recreational park, children play areas, and surrounding green belt.',
  },
  {
    id: 'mis-02',
    title: 'High Street Bazaar Plastic-Free Drive',
    neighborhood: 'Goal Chowk to High Street',
    date: 'Saturday, 4 Oct',
    time: '08:00 AM – 11:00 AM',
    participantsCount: 16,
    maxParticipants: 30,
    rewardPoints: 250,
    status: 'Upcoming',
    organizer: 'Traders Association & Shehri Volunteers',
    wasteTargetKg: 200,
    collectedKg: 0,
    description: 'Distribute biodegradable shop bags and clear back-alley sorting zones behind historic market.',
  },
  {
    id: 'mis-03',
    title: 'Canal Road Heritage Walk Cleanup',
    neighborhood: 'Lower Bari Doab Canal Track',
    date: 'Completed 20 Sep',
    time: '06:30 AM – 09:30 AM',
    participantsCount: 35,
    maxParticipants: 35,
    rewardPoints: 180,
    status: 'Completed',
    organizer: 'Montgomery Walking Club',
    wasteTargetKg: 120,
    collectedKg: 138,
    description: 'Restored 2 km of walking trails with 138 kg waste collected and safely dispatched for recycling.',
  },
];

export const MOCK_LEADERBOARD: CitizenRank[] = [
  {
    id: 'c-1',
    rank: 1,
    name: 'Tariq Mehmood',
    avatarSeed: 'TM',
    neighborhood: 'Farid Town',
    points: 2450,
    reportsResolved: 34,
    badgeTitle: 'Chief Eco Champion',
  },
  {
    id: 'c-2',
    rank: 2,
    name: 'Ayesha Malik',
    avatarSeed: 'AM',
    neighborhood: 'Civil Lines',
    points: 2180,
    reportsResolved: 29,
    badgeTitle: 'Waste Crusader',
  },
  {
    id: 'c-3',
    rank: 3,
    name: 'Bilal Mengrani',
    avatarSeed: 'BM',
    neighborhood: 'Canal View',
    points: 1940,
    reportsResolved: 26,
    badgeTitle: 'Civic Guardian',
  },
  {
    id: 'c-4',
    rank: 4,
    name: 'Zubair Akhtar',
    avatarSeed: 'ZA',
    neighborhood: 'High Street',
    points: 1620,
    reportsResolved: 21,
    badgeTitle: 'Neighborhood Lead',
  },
  {
    id: 'c-5',
    rank: 5,
    name: 'Dr. Fatima Noor',
    avatarSeed: 'FN',
    neighborhood: 'College Road',
    points: 1480,
    reportsResolved: 19,
    badgeTitle: 'Health & Clean Advocate',
  },
  {
    id: 'c-user',
    rank: 8,
    name: 'Hamza Khan (You)',
    avatarSeed: 'HK',
    neighborhood: 'Farid Town',
    points: 850,
    reportsResolved: 3,
    badgeTitle: 'Eco Vigilante',
    isCurrentUser: true,
  },
];

export const NEIGHBORHOOD_LEADERBOARD = [
  { name: 'Farid Town', reports: 68, activeVolunteers: 114, points: 12400 },
  { name: 'Civil Lines', reports: 45, activeVolunteers: 82, points: 9600 },
  { name: 'High Street & Goal Chowk', reports: 59, activeVolunteers: 76, points: 8950 },
  { name: 'Canal View Colony', reports: 31, activeVolunteers: 49, points: 6100 },
  { name: 'College Road Area', reports: 27, activeVolunteers: 43, points: 4800 },
];
