/**
 * ============================================================================
 * MOCK REWARDS CATALOG — LOCAL SAHIWAL CIVIC BUSINESS PARTNERSHIPS
 * ============================================================================
 * 
 * NOTE FOR PRODUCTION:
 * This file contains realistic demonstration and placeholder rewards for local
 * Sahiwal businesses and community vendors (Farid Town, High Street, College Road,
 * Canal Road, Civil Lines).
 * 
 * When real commercial sponsors, municipal merchant alliances, or telco APIs
 * are onboarded, they can be swapped in here or loaded directly from a Firestore
 * `rewards` collection without changing the UI, redemption verification, or CleanPoints
 * deduction logic.
 * ============================================================================
 */

import { RewardItem } from '../types';

export const MOCK_REWARDS: RewardItem[] = [
  {
    id: 'rew-sahiwal-mart-100',
    title: 'Rs. 100 Off Grocery Bill',
    titleUrdu: 'گروسری بل پر ۱۰۰ روپے کی چھوٹ',
    businessName: 'Al-Madina Supermarket',
    businessNameUrdu: 'المدینہ سپر مارکیٹ',
    businessAddress: 'Main Market, Farid Town, Sahiwal',
    businessAddressUrdu: 'مین مارکیٹ، فرید ٹاؤن، ساہیوال',
    category: 'supermarket',
    pointsCost: 100,
    discountValue: 'Rs. 100 Off',
    discountValueUrdu: '۱۰۰ روپے رعایت',
    description: 'Enjoy Rs. 100 flat discount on any household grocery purchase of Rs. 1,000 or above.',
    descriptionUrdu: '۱۰۰۰ روپے یا اس سے زائد کی گھریلو خریداری پر ۱۰۰ روپے کی فوری رعایت حاصل کریں۔',
    terms: 'Valid on in-store purchases. One voucher per billing transaction. Not redeemable for cash.',
    termsUrdu: 'دکان پر خریداری کے لیے قابل قبول ہے۔ ایک بل پر ایک واؤچر لاگو ہوگا۔',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Popular Choice',
    badgeTagUrdu: 'مقبول انتخاب',
    validDays: 30,
  },
  {
    id: 'rew-fresh-bakery-chai',
    title: 'Free Karak Chai & Samosa Combo',
    titleUrdu: 'مفت کڑک چائے اور سموسہ کمبو',
    businessName: 'Gourmet Sweets & Bakers',
    businessNameUrdu: 'گورمے سویٹس اینڈ بیکرز',
    businessAddress: 'High Street, Near Railway Station, Sahiwal',
    businessAddressUrdu: 'ہائی اسٹریٹ، ریلوے اسٹیشن کے قریب، ساہیوال',
    category: 'food',
    pointsCost: 50,
    discountValue: 'Free Item (Rs. 90 Value)',
    discountValueUrdu: 'مفت آئٹم (۹۰ روپے مالیت)',
    description: 'Grab a hot cup of authentic Sahiwali Karak Chai paired with a crispy vegetable/potato samosa.',
    descriptionUrdu: 'ساہیوال کی خاص کڑک چائے کے ساتھ کرسپی سموسے کا مفت لطف اٹھائیں۔',
    terms: 'Show active voucher code at counter before ordering. Valid 8 AM to 10 PM daily.',
    termsUrdu: 'آرڈر سے پہلے کاؤنٹر پر ایکٹو واؤچر کوڈ دکھائیں۔ روزانہ صبح ۸ سے رات ۱۰ تک۔',
    logoUrl: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Low Points',
    badgeTagUrdu: 'کم پوائنٹس',
    validDays: 14,
  },
  {
    id: 'rew-mobile-load-100',
    title: 'Rs. 100 Mobile Load Voucher',
    titleUrdu: '۱۰۰ روپے کا موبائل لوڈ واؤچر',
    businessName: 'Punjab EasyLoad & Telecom',
    businessNameUrdu: 'پنجاب ایزی لوڈ اینڈ ٹیلی کام',
    businessAddress: 'College Road, Opp. Govt. Post Graduate College, Sahiwal',
    businessAddressUrdu: 'کالج روڈ، گورنمنٹ پوسٹ گریجویٹ کالج کے سامنے، ساہیوال',
    category: 'mobile_load',
    pointsCost: 100,
    discountValue: 'Rs. 100 Balance',
    discountValueUrdu: '۱۰۰ روپے بیلنس',
    description: 'Receive Rs. 100 mobile top-up for Jazz, Zong, Telenor, or Ufone prepay numbers.',
    descriptionUrdu: 'جاز، زونگ، ٹیلی نار یا یوفون نمبر کے لیے ۱۰۰ روپے کا موبائل بیلنس لوڈ حاصل کریں۔',
    terms: 'Instant top-up at shop upon showing verification code. Pre-paid cellular numbers only.',
    termsUrdu: 'دکان پر کوڈ دکھانے پر فوری ایزی لوڈ منتقل کیا جائے گا۔ صرف پری پیڈ نمبرز کے لیے۔',
    logoUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Instant Top-Up',
    badgeTagUrdu: 'فوری لوڈ',
    validDays: 30,
  },
  {
    id: 'rew-canal-cafe-burger',
    title: '20% Off Dine-In or Takeaway',
    titleUrdu: 'کھانے اور ٹیک اوے پر ۲۰٪ رعایت',
    businessName: 'Canal View Cafe & Fast Food',
    businessNameUrdu: 'کینال ویو کیفے اینڈ فاسٹ فوڈ',
    businessAddress: 'Canal Bank Road, Sector 1, Sahiwal',
    businessAddressUrdu: 'کینال بینک روڈ، سیکٹر ۱، ساہیوال',
    category: 'food',
    pointsCost: 150,
    discountValue: '20% Discount',
    discountValueUrdu: '۲۰٪ رعایت',
    description: 'Get 20% off your entire meal bill including Burgers, Pizzas, Biryani, and fresh mocktails.',
    descriptionUrdu: 'برگر، پیزا اور کھانے کے کل بل پر ۲۰ فیصد کی رعایت حاصل کریں۔',
    terms: 'Valid for dine-in and takeaway. Maximum discount limit Rs. 500 per receipt.',
    termsUrdu: 'ڈائن ان اور ٹیک اوے دونوں کے لیے۔ زیادہ سے زیادہ ۵۰۰ روپے تک کی رعایت۔',
    logoUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Top Rated',
    badgeTagUrdu: 'بہترین ریٹنگ',
    validDays: 21,
  },
  {
    id: 'rew-sahiwal-books-stationery',
    title: 'Rs. 150 Off Books & Stationery',
    titleUrdu: 'کتب و اسٹیشنری پر ۱۵۰ روپے رعایت',
    businessName: 'Iqbal Book Depot & Stationery',
    businessNameUrdu: 'اقبال بک ڈپو اینڈ اسٹیشنری',
    businessAddress: 'Liaquat Chowk, Jogi Chowk Road, Sahiwal',
    businessAddressUrdu: 'لیاقت چوک، جوگی چوک روڈ، ساہیوال',
    category: 'stationery',
    pointsCost: 120,
    discountValue: 'Rs. 150 Off',
    discountValueUrdu: '۱۵۰ روپے رعایت',
    description: 'Save Rs. 150 on school notebooks, textbooks, art supplies, and writing instruments.',
    descriptionUrdu: 'اسکول کی کاپیوں، کتب، پینٹنگ اور اسٹیشنری کے سامان پر ۱۵۰ روپے کی چھوٹ۔',
    terms: 'Minimum purchase of Rs. 600 required. Cannot be merged with seasonal discount offers.',
    termsUrdu: 'کم از کم ۶۰۰ روپے کی خریداری پر لاگو۔ دیگر رعایتی آفرز کے ساتھ شامل نہیں۔',
    logoUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Education Partner',
    badgeTagUrdu: 'تعلیمی پارٹنر',
    validDays: 45,
  },
  {
    id: 'rew-shehri-pharmacy-15',
    title: '15% Off Healthcare & First Aid',
    titleUrdu: 'طبی ادویات پر ۱۵٪ رعایت',
    businessName: 'Shifa Medicos & General Store',
    businessNameUrdu: 'شفا میڈیکوز اینڈ جنرل اسٹور',
    businessAddress: 'District Hospital Road, Civil Lines, Sahiwal',
    businessAddressUrdu: 'ڈسٹرکٹ ہسپتال روڈ، سول لائنز، ساہیوال',
    category: 'pharmacy',
    pointsCost: 100,
    discountValue: '15% Off Health Items',
    discountValueUrdu: '۱۵٪ طبی رعایت',
    description: '15% flat discount on vitamins, first-aid sanitizers, masks, and personal hygiene supplies.',
    descriptionUrdu: 'وٹامنز، فرسٹ ایڈ، ماسک، سینیٹائزر اور حفظان صحت کی اشیاء پر ۱۵ فیصد رعایت۔',
    terms: 'Valid on OTC health supplements and wellness supplies. Prescription required for specific items.',
    termsUrdu: 'عام ادویات اور سینیٹری اشیاء پر قابل قبول ہے۔',
    logoUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Health & Wellness',
    badgeTagUrdu: 'صحت و تندرستی',
    validDays: 30,
  },
  {
    id: 'rew-punjab-superstore-300',
    title: 'Rs. 300 Off Big Basket Shopping',
    titleUrdu: 'بڑی خریداری پر ۳۰۰ روپے رعایت',
    businessName: 'Rahim Cash & Carry',
    businessNameUrdu: 'رحیم کیش اینڈ کیری',
    businessAddress: 'Circular Road, Near Stadium, Sahiwal',
    businessAddressUrdu: 'سرکلر روڈ، اسٹیڈیم کے قریب، ساہیوال',
    category: 'supermarket',
    pointsCost: 250,
    discountValue: 'Rs. 300 Off',
    discountValueUrdu: '۳۰۰ روپے رعایت',
    description: 'Get Rs. 300 instant discount on mega grocery baskets and cooking oil cartons.',
    descriptionUrdu: 'ماہانہ راشن اور کچن گروسری کی خریداری پر ۳۰۰ روپے کی فوری رعایت حاصل کریں۔',
    terms: 'Valid on min cart total of Rs. 3,000. Voucher barcode scanned at checkout counter.',
    termsUrdu: 'کم از کم ۳۰۰۰ روپے کے بل پر لاگو۔ بلنگ کاؤنٹر پر بارکوڈ اسکین کروائیں۔',
    logoUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'High Value',
    badgeTagUrdu: 'بڑی بچت',
    validDays: 30,
  },
  {
    id: 'rew-mobile-load-200',
    title: 'Rs. 200 Mega Mobile Recharge',
    titleUrdu: '۲۰۰ روپے میگا موبائل ریچارج',
    businessName: 'Sahiwal Communication Hub',
    businessNameUrdu: 'ساہیوال کمیونیکیشن ہب',
    businessAddress: 'Church Road, Saddar Bazaar, Sahiwal',
    businessAddressUrdu: 'چرچ روڈ، صدر بازار، ساہیوال',
    category: 'mobile_load',
    pointsCost: 200,
    discountValue: 'Rs. 200 Load',
    discountValueUrdu: '۲۰۰ روپے لوڈ',
    description: 'Super recharge for internet data packages or call bundles on any Pakistani network.',
    descriptionUrdu: 'کسی بھی نیٹ ورک پر انٹرنیٹ پیکیج یا کال بنڈل کے لیے ۲۰۰ روپے کا فوری بیلنس لوڈ۔',
    terms: 'Valid for Jazz, Telenor, Zong, and Ufone. Verified in 2 minutes at vendor shop.',
    termsUrdu: 'تمام نیٹ ورکس کے لیے کارآمد۔ دکان پر دو منٹ میں لوڈ منتقل۔',
    logoUrl: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Digital Top-Up',
    badgeTagUrdu: 'ڈیجیٹل ریچارج',
    validDays: 60,
  },
  {
    id: 'rew-vip-chaman-icecream',
    title: 'Free Family Ice Cream Tub',
    titleUrdu: 'مفت فیملی آئس کریم ٹب',
    businessName: 'Chaman Ice Cream & Falooda',
    businessNameUrdu: 'چمن آئس کریم اینڈ فالودہ',
    businessAddress: 'Girls College Chowk, High Street, Sahiwal',
    businessAddressUrdu: 'گرلز کالج چوک، ہائی اسٹریٹ، ساہیوال',
    category: 'food',
    pointsCost: 300,
    discountValue: 'Free Tub (Rs. 450 Value)',
    discountValueUrdu: 'مفت فیملی ٹب (۴۵۰ روپے)',
    description: 'Redeem a 1-Liter premium Kulfa/Pista/Mango ice cream tub with real almond & saffron toppings.',
    descriptionUrdu: '۱ لیٹر خالص پستہ، قلفہ یا مینگو آئس کریم کا فیملی ٹب بالکل مفت حاصل کریں۔',
    terms: 'Valid on takeaway. Show verified app screen code to the manager.',
    termsUrdu: 'ٹیک اوے کے لیے دستیاب۔ کاؤنٹر مینیجر کو ایکٹو سکرین کوڈ دکھائیں۔',
    logoUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Community Favorite',
    badgeTagUrdu: 'پسندیدہ ٹریٹ',
    validDays: 20,
  },
  {
    id: 'rew-grand-champion-500',
    title: 'Rs. 500 Sahiwal Civic Super Voucher',
    titleUrdu: '۵۰۰ روپے ساہیوال شہری گرینڈ واؤچر',
    businessName: 'Al-Haram Super Mart & Electronics',
    businessNameUrdu: 'الحرم سپر مارٹ اینڈ الیکٹرانکس',
    businessAddress: 'Main GT Road, Near bypass crossing, Sahiwal',
    businessAddressUrdu: 'مین جی ٹی روڈ، بائی پاس کے قریب، ساہیوال',
    category: 'general',
    pointsCost: 500,
    discountValue: 'Rs. 500 Grand Cash Off',
    discountValueUrdu: '۵۰۰ روپے نقد رعایت',
    description: 'Elite civic champion reward! Get Rs. 500 flat discount across any store department.',
    descriptionUrdu: 'اعلیٰ ماحولیاتی چیمپئن انعام! مارٹ کے کسی بھی شعبے میں ۵۰۰ روپے کی مکمل رعایت۔',
    terms: 'Exclusive for high-tier civic volunteers. No minimum purchase restriction.',
    termsUrdu: 'اعلیٰ درجے کے شہری رضاکاروں کے لیے۔ کم از کم خریداری کی کوئی شرط نہیں۔',
    logoUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=120&auto=format&fit=crop&q=80',
    badgeTag: 'Elite Champion Tier',
    badgeTagUrdu: 'چیمپئن اعزاز',
    validDays: 60,
  },
];
